### ISSUE TITLE
FOUNDATIONS: Add Support for Http WASM

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/RESTFulSense#25]

**Comment by rcruzfreelance** [comment]
How can I help for this one?

**Comment by hassanhabib** [comment]
@rcruzfreelance we need to understand how the WASM `Http` client works and apply all exception handling to it. After an initial investiagation my thought is that no change needed. Let's start with this:
1. Create a simple Blazor WASM project
2. Try RESTFulSense with it
3. Observe and see if that works

**Comment by rcruzfreelance** [comment]
Hello Hassan I tried creating and testing the RESTFuleSense with a WASM project and got the following error
![image](https://user-images.githubusercontent.com/53588704/143773151-682808c9-7ef7-46a9-aaf5-043c8e215eb4.png)


Some addtional info from an auto generated code
![image](https://user-images.githubusercontent.com/53588704/143773167-2d202b91-cec6-45d9-b4f3-30b8c3cb29e1.png)


After some investigation I found a github issue similar to this saying that  Blazor WebAssembly application cannot be referenced by MVC binaries.

https://github.com/dotnet/aspnetcore/issues/27373

**Comment by rcruzfreelance** [comment]
From what I'm understanding we just need to replace  the ObjectResult and ValidationProblemDetails with our own classes in order to not depend on the Microsoft.AspNetCore.Mvc since is not supported on web assembly project. Let me know what you think of this. We could also create a new library(RESTFulSense.BlazorWebAssembly for example) to seperate them so people can have flexibility of picking the library

**Comment by hassanhabib** [comment]
@rcruzfreelance that might be the only change needed really.
@BrianLParker what else is different when calling the HttpClient in WASM Blazor?

**Comment by hassanhabib** [comment]
This is closed. thanks @BrianLParker
